version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 4321:4321
      - 9228:9228

    volumes:
      - ./backend:/app/
      
  frontend:
    build: ./frontend
    ports:
      - 4200:4200
      - 9229:9229

  database:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
