version: "3"
services:
  backend:
    build: ./backend
    ports:
      - 4321:4321
      - 9228:9228

    volumes:
      - ./backend:/app/
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - 4200:4200
      - 9229:9229
    depends_on:
      - backend

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      # pense à mettre à jour pour garder tes données
    ports:
      - 5433:5432
